# Generated by Django 4.1.7 on 2023-03-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nout name')),
                ('img', models.ImageField(upload_to='images', verbose_name='Nout image')),
                ('price', models.IntegerField(verbose_name='Nout price')),
                ('about', models.TextField(verbose_name='Nout about')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Nout create date')),
            ],
            options={
                'verbose_name': 'Nout',
                'verbose_name_plural': 'Nouts',
                'ordering': ['date'],
            },
        ),
    ]
