# Generated by Django 4.1.7 on 2023-03-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nout',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Nout slug'),
        ),
    ]
